spring.application.name=cloud-monitor-backend

# SQLite Database Configuration
spring.datasource.url=jdbc:sqlite:cloudmonitor.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080

# Security
spring.security.user.name=admin
spring.security.user.password=admin
